# Generated by Django 4.2.7 on 2024-04-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=' ', upload_to='category'),
        ),
    ]
